# Generated by Django 4.0.5 on 2022-06-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0004_alter_video_video_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['video_title'], name='youtube_api_video_t_ddc142_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['description'], name='youtube_api_descrip_464849_idx'),
        ),
    ]
