# Generated by Django 4.0.5 on 2022-06-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('published_date_time', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['published_date_time'], name='youtube_api_publish_50ee01_idx'),
        ),
    ]
