# Generated by Django 4.0.5 on 2022-06-17 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(null=True),
        ),
    ]
